sudo: false
language: rust

rust: stable

env:
  global:
    - secure: pIERpF0cNsOP5OXPZH6wZgL4CsruAV7DUf8W35mcB1rIDKuPFnMkqOy7Y2vVEKNgSrUNVwLb8ym4qqy3QRQWy0vZE5fJdhCa0oePeAfr+Q3Y0zBZHiVlNWy9nWZsYKu4O8SXT8xK4dpLDwwgj3/s5sCJWdLC657QkzJRbQaQc7IbGW+FkWzwczzO2PKnSgjtXRRqpOdt3RwuiwBWBvCPYsMACOtYBWTOpjp3tKpLn5eHKhW7rjydKDwyERSOCNNJJ7j9QVQ5KrbMfBh4Nrap2tDLI8Pn3sDriN3ykzh++lN3VqucglJCrmzoCLYpURlvuNdhVIqWqVPFU9I+jl5h0n7iI4xa5bbRFGWPDfKdF9xJFz+C37fq3F2glHXygJaCaWI/n0WWSSs0Jf++l+Jt/m7ljA0KHB3TnjA5+GlUBTg9GBqCNgiaWGy6Lo1sKSE5of9ylXg2fZz6fgYmiRrBvGfgBqVbZ0vUzQGiZGyWHmlDUqdwCzx8k/9ZNeeZfVivzsFqi5468iUESkto/KLLPqLkFDUtXLEz5MZ3gluIAjDepDT68SelDWrDocSlQSe54IFr8WdQv1Z+FIVLzzD54c5AXPWtlJH1OWigeJXaN3PyfXWBKla7vh4SgzlppgaNUUZ3RPR5RabDv4XmsWU9FqnUrSRlCay9TlORWs8o4GY=
  matrix:
    - TARGET=x86_64-unknown-linux-gnu
    - TARGET=x86_64-unknown-linux-musl

install:
  - sh ci/install.sh

script:
  - sh ci/run.sh

notifications:
  email:
    on_success: never

deploy:
  provider: script
  script: ci/deploy.sh
  skip_cleanup: true
  on:
    tags: true
