sudo: false
language: rust

rust: stable

os:
  - linux
  - osx

matrix:
  # Clean the whole matrix
  exclude:
    - os: linux
    - os: osx
  # Add targets
  include:
    - os: linux
      env: TARGET=arm-unknown-linux-gnueabihf
      addons:
        apt:
          packages:
            - gcc-arm-linux-gnueabihf
            - libc6-armhf-cross
            - libc6-dev-armhf-cross
    - os: linux
      env: TARGET=i686-unknown-linux-gnu
      addons:
        apt:
          packages:
            - gcc-multilib
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      env: TARGET=x86_64-unknown-linux-musl
    - os: osx
      env: TARGET=x86_64-apple-darwin

install:
  - sh ci/install.sh

script:
  - sh ci/script.sh

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: pF/Y7qIeKjrunbI3M+JSiTwsTey77Vy+Xi7KpLRrxBHGgWUMNhivJ6QIDvZfrl6qk1TDAO+3GVZPFfMcqz6s11zkVDfwPaTY9fpueaC8ZxdoeYkhJX3soTD3KUKtMMtq/GFbdvGJTs3EWHKnyQVdY8SUEj/dK72HsITP0mhw9HjznWDOy5Xb1SgdB3lKvyLIBHOQSJXI6cELDuiawQtkTwIqBFiv3xRN4+jXrcIqpWF7515PIas5L9PfT5bZhAXoTSVIuqr3TI/1hsJMbinHXhizz+eMNwqLYUarLJpyYIU/QgJ3II8UfxI1CXUEgAg7QTrPJjJ3/wCh83kTdYBbsWIdotYdVjraFMhQZ+dl2cHFBCptFUqDfoMlwvi3yS9KKNSn0Fajqky0gBRyOCA4Wyc1+CkR4qmGdG/1G8t0oyI1GL2kDDNqmGHgmAN0D0RmijFy+KOgu5OVJFhHRgmqW5kX2NZCQ9zkmtGdWZ+SVEymTN3QkxMtHv6RJ9LUa2HaC8vCGB7U+4JeLUWh8yb5kzXi+paMSz4nDmDK2JCa15zp2lESHUALKh/hejFBPW2vObgBkYzV0gL0wtNJL8UohlgkzJuBa8Q4cr19jP9HsD64H3I2wzZ0W/hXVrg2dlqbWG5tqeZpRv6b7ix6GJLZsfOgZ/FjlPhGcp22OvmNOgc=
  file: deploy/hello-${TRAVIS_TAG}-${TARGET}.tar.gz
  skip_cleanup: true
  on:
    tags: true

branches:
  only:
    # Pushes and PR to the master branch
    - master
    # Ruby regex to match tags. Required, or travis won't trigger deploys
    - /^v\d+\.\d+\.\d+.*$/

notifications:
  email:
    on_success: never
