sudo: false

language: rust

# NOTE This configuration has only be tested on the stable channel
rust: stable

os:
  - linux
  - osx

env:
  global:
    # This will be part of the release tarball
    # TODO change the project name
    - PROJECT_NAME=rust-everywhere

matrix:
  # Clear the whole matrix
  exclude:
    - os: linux
    - os: osx
  # Add each target manually
  # TODO feel free to remove targets you are not interested in
  # TODO you may want to install packages for specific build jobs, use the addons.apt.packages
  # pattern shown below
  include:
    # WARNING Experimental target. Tests are not executed. And by the next Rust stable release, this
    # target will be replaced by `armv7-unknown-linux-gnueabihf`.
    - os: linux
      env: TARGET=arm-unknown-linux-gnueabihf
      # Extra packages only for this build job
      addons:
        apt:
          packages:
            # Cross compiler and cross compiled C libraries
            - gcc-arm-linux-gnueabihf
            - libc6-armhf-cross
            - libc6-dev-armhf-cross
    - os: linux
      env: TARGET=i686-unknown-linux-gnu
      addons:
        apt:
          packages:
            # Cross compiler and cross compiled C libraries
            - gcc-multilib
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      env: TARGET=x86_64-unknown-linux-musl
    - os: osx
      env: TARGET=i686-apple-darwin
    - os: osx
      env: TARGET=x86_64-apple-darwin

install:
  - sh ci/install.sh

script:
  - sh ci/script.sh

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  provider: releases
  # TODO Regenerate this api_key for your project, this one won't work for you. Here's how:
  # - Go to 'https://github.com/settings/tokens/new' and generate a Token with only the
  # `public_repo` scope enabled
  # - Call `travis encrypt $github_token` where $github_token is the token you got in the previous
  # step and `travis` is the official Travis CI gem (see https://rubygems.org/gems/travis/)
  # - Enter the "encrypted value" below
  api_key:
    secure: aLyVgmimaRMCvh2YF4ek0ZseWqKpqCSrvvYdf5rxhZUBnYK+KKlHBsPudtmWbHTh19PPC1C3wSHa8y94IObGl3iRRTICh5e/Oz9xzCiPYlQ0ZGmtM+MfRtUq2xFRc6aaAkrnfW0ur3uxk4a7ZBIOMg3D7kG7Ah4dg5dVf26OmpSBdEijo9bcvOLHXwZIc1bby+MJl8kxzdlwaV7UTrqHQFh+tmMsoO0GQcQpCP3y45f5/8aTkHRmnC1IKCiHKDZpRFDWhdoz02NGWcCnoH43iSwOobe1jacHicmZ7dNHKT/e1tfUIPpbO81fvQ7FHifvBRoO64Wvl5l/IaoDcngv6o11JlWRxIuZnr01oDv+DW8kv9POLYeh2xzMaQkZ8NkPZl82hqr8t0q0OtXZjm/Hysdcvr0T26hbwqs1sOkAAaeRdR0zl/Log53hNqM4HaZZ0CnKGU8dSatC+NOgHEfz68fHArf8DUdKIr3By73tD7T7kJjT1h6F+4E2nYVbHrl20/PV+XO97+9LUNOy6IhbQN0hQjoHVra5oWcZy9WiWgX8IV74yw6vEAQh6XDUWtU9XR7Tl1TjaO/mR8MgOJuQkLt58QWPs50BgUD9XSvDVIurPilZ0bQzvM7js6nTupmd3oaZiYSZCxOTj0LpV34fdEaFX0qSlrSFQw6YYMAawks=
  file: ${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.tar.gz
  # don't delete the artifacts from previous phases
  skip_cleanup: true
  # deploy when a new tag is pushed
  on:
    tags: true

branches:
  only:
    # Pushes and PR to the master branch
    - master
    # IMPORTANT Ruby regex to match tags. Required, or travis won't trigger deploys when a new tag
    # is pushed. This regex matches semantic versions like v1.2.3-rc4+2016.02.22
    - /^v\d+\.\d+\.\d+.*$/

notifications:
  email:
    on_success: never
