environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo build
  - cargo run
  - cargo build --release

after_test:
  - 7z a hello-%TARGET%.zip target\release\hello.exe

artifacts:
  - path: hello-$(TARGET).zip
    name: hello-$(TARGET).zip
    type: zip

deploy:
  description: 'Windows release'
  artifact: hello-$(TARGET).zip
  auth_token:
    secure: 1+6upr5ZBEd0nETJIizhrGdu8aU8RlB2g6cwRzf3/Si1ruhwif58ddJYY1+bvngA
  provider: GitHub
  on:
    appveyor_repo_tag: true

branches:
  only:
    - master
