environment:
  matrix:
  - TARGET: i686-pc-windows-gnu
    MSYS2_BITS: 32
  - TARGET: i686-pc-windows-msvc
  - TARGET: x86_64-pc-windows-gnu
    MSYS2_BITS: 64
  - TARGET: x86_64-pc-windows-msvc
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - if defined MSYS2_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS2_BITS%\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo build --verbose
  - cargo run
  - cargo test
  - cargo build --release

after_test:
  - mkdir deploy
  - copy target\release\hello.exe deploy
  - cd deploy
  - 7z a hello-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip hello.exe

artifacts:
  - path: deploy\hello-$(APPVEYOR_REPO_TAG_NAME)-$(TARGET).zip
    name: hello-$(APPVEYOR_REPO_TAG_NAME)-$(TARGET).zip
    type: zip

deploy:
  description: 'Windows release'
  artifact: /.*\.zip/
  auth_token:
    secure: 1+6upr5ZBEd0nETJIizhrGdu8aU8RlB2g6cwRzf3/Si1ruhwif58ddJYY1+bvngA
  provider: GitHub
  on:
    appveyor_repo_tag: true

branches:
  only:
    - master
